"use client"

import { Clock, FileText, Shield, TrendingUp } from "lucide-react"

export function VaultInfo() {
  return (
    <div className="rounded-2xl border border-white/10 bg-[#0d0d0d] p-6">
      <h3 className="font-semibold text-foreground mb-4">How It Works</h3>

      <div className="grid grid-cols-2 gap-4">
        <div className="p-4 rounded-xl bg-white/[0.02] border border-white/5">
          <div className="p-2 rounded-lg bg-[#8b5cf6]/10 w-fit mb-3">
            <TrendingUp className="h-4 w-4 text-[#8b5cf6]" />
          </div>
          <h4 className="font-medium text-foreground text-sm mb-1">Earn Trading Fees</h4>
          <p className="text-xs text-muted-foreground">
            NLP holders earn 70% of all trading fees generated by the protocol.
          </p>
        </div>

        <div className="p-4 rounded-xl bg-white/[0.02] border border-white/5">
          <div className="p-2 rounded-lg bg-[#3b82f6]/10 w-fit mb-3">
            <Shield className="h-4 w-4 text-[#3b82f6]" />
          </div>
          <h4 className="font-medium text-foreground text-sm mb-1">Delta-Neutral</h4>
          <p className="text-xs text-muted-foreground">
            The vault is algorithmically hedged to minimize directional exposure.
          </p>
        </div>

        <div className="p-4 rounded-xl bg-white/[0.02] border border-white/5">
          <div className="p-2 rounded-lg bg-[#22c55e]/10 w-fit mb-3">
            <Clock className="h-4 w-4 text-[#22c55e]" />
          </div>
          <h4 className="font-medium text-foreground text-sm mb-1">No Lock-up Period</h4>
          <p className="text-xs text-muted-foreground">Withdraw your funds at any time with instant settlement.</p>
        </div>

        <div className="p-4 rounded-xl bg-white/[0.02] border border-white/5">
          <div className="p-2 rounded-lg bg-[#f59e0b]/10 w-fit mb-3">
            <FileText className="h-4 w-4 text-[#f59e0b]" />
          </div>
          <h4 className="font-medium text-foreground text-sm mb-1">Audited Contracts</h4>
          <p className="text-xs text-muted-foreground">Smart contracts audited by leading security firms.</p>
        </div>
      </div>

      {/* Stats Footer */}
      <div className="mt-6 pt-4 border-t border-white/5 grid grid-cols-3 gap-4">
        <div>
          <span className="text-xs text-muted-foreground block mb-1">Depositors</span>
          <span className="font-mono font-semibold text-foreground">1,247</span>
        </div>
        <div>
          <span className="text-xs text-muted-foreground block mb-1">Total Earned</span>
          <span className="font-mono font-semibold text-[#22c55e]">$842,500</span>
        </div>
        <div>
          <span className="text-xs text-muted-foreground block mb-1">Vault Age</span>
          <span className="font-mono font-semibold text-foreground">127 days</span>
        </div>
      </div>
    </div>
  )
}
