/**
 * Noether Protocol - Contract Configuration
 *
 * This file contains contract addresses and network configuration.
 *
 * After running `scripts/deploy.sh`, the deployed contract IDs will be
 * saved to `lib/deployed_contracts.json`. Update the values below or
 * set environment variables:
 *
 *   NEXT_PUBLIC_MARKET_CONTRACT_ID
 *   NEXT_PUBLIC_VAULT_CONTRACT_ID
 *   NEXT_PUBLIC_ORACLE_CONTRACT_ID
 *   NEXT_PUBLIC_USDC_TOKEN_CONTRACT_ID
 */

// Try to import deployed contracts (generated by deploy.sh)
let deployedContracts: {
  contracts?: {
    market?: string;
    vault?: string;
    oracle?: string;
    usdc?: string;
  };
} = {};

try {
  // This will be available after running deploy.sh
  deployedContracts = require('./deployed_contracts.json');
} catch {
  // File doesn't exist yet - using placeholders
}

// Network Configuration
export const NETWORK = {
  name: "testnet",
  passphrase: "Test SDF Network ; September 2015",
  rpcUrl: "https://soroban-testnet.stellar.org",
  horizonUrl: "https://horizon-testnet.stellar.org",
} as const;

// Contract IDs - Priority: Environment Variables > Deployed JSON > Placeholder
export const CONTRACTS = {
  // Market contract for trading positions
  MARKET: process.env.NEXT_PUBLIC_MARKET_CONTRACT_ID
    || deployedContracts.contracts?.market
    || "PLACEHOLDER_MARKET_CONTRACT_ID",

  // Vault contract for liquidity provision
  VAULT: process.env.NEXT_PUBLIC_VAULT_CONTRACT_ID
    || deployedContracts.contracts?.vault
    || "PLACEHOLDER_VAULT_CONTRACT_ID",

  // Oracle contract for price feeds
  ORACLE: process.env.NEXT_PUBLIC_ORACLE_CONTRACT_ID
    || deployedContracts.contracts?.oracle
    || "PLACEHOLDER_ORACLE_CONTRACT_ID",

  // USDC token contract (testnet)
  USDC_TOKEN: process.env.NEXT_PUBLIC_USDC_TOKEN_CONTRACT_ID
    || deployedContracts.contracts?.usdc
    || "PLACEHOLDER_USDC_TOKEN_CONTRACT_ID",

  // NLP token contract (vault LP token)
  NLP_TOKEN: "PLACEHOLDER_NLP_TOKEN_CONTRACT_ID",
} as const;

// Asset definitions
export const ASSETS = {
  STELLAR: { symbol: "XLM", decimals: 7 },
  USDC: { symbol: "USDC", decimals: 7 },
} as const;

// Precision for calculations (7 decimals - Stellar standard)
export const PRECISION = 10_000_000;

// Trading constants
export const TRADING = {
  MAX_LEVERAGE: 10, // 10x max leverage
  MIN_COLLATERAL: 10_000_000, // 1 USDC minimum (7 decimals)
  TAKER_FEE_BPS: 5, // 0.05% taker fee
  MAKER_FEE_BPS: 2, // 0.02% maker fee
} as const;

// Helper to format amounts with precision
export function toContractAmount(humanAmount: number): bigint {
  return BigInt(Math.floor(humanAmount * PRECISION));
}

// Helper to parse contract amounts to human readable
export function fromContractAmount(contractAmount: bigint | number): number {
  return Number(contractAmount) / PRECISION;
}
